
name: Scheduled Job

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at 00:00 UTC

  workflow_dispatch: # Manual workflow dispatch trigger
    inputs:
      custom_parameter: # Add any custom parameters you need
        description: 'Parameter description'
        required: false


jobs:
  run-script:
    runs-on: ubuntu-latest

    env:
      SPOTIPY_CLIENT_ID: ${{ secrets.SPOTIPY_CLIENT_ID }}
      SPOTIPY_CLIENT_SECRET: ${{ secrets.SPOTIPY_CLIENT_SECRET }}
      SPOTIPY_USERNAME: ${{ secrets.SPOTIPY_USERNAME }}
      SPOTIPY_PLAYLIST_URI: ${{ secrets.SPOTIPY_PLAYLIST_URI }}
      # Add other secrets as needed

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Debug information
        run: |
          echo "SPOTIPY_CLIENT_ID: $SPOTIPY_CLIENT_ID"
          echo "SPOTIPY_CLIENT_SECRET: $SPOTIPY_CLIENT_SECRET"
          echo "SPOTIPY_USERNAME: $SPOTIPY_USERNAME"
          echo "SPOTIPY_PLAYLIST_URI: $SPOTIPY_PLAYLIST_URI"

      - name: Run Script
        run: python ./code/singles_scrapper.py
        env:
          PYTHONUNBUFFERED: 1
          SPOTIPY_CACHE_PATH: ${{ env.SPOTIPY_CACHE_PATH }}
        continue-on-error: true  # Continue even if the script fails

      

    outputs:
      verbosity: 'normal'  # or 'debug'
